spring.application.name=FileUp


# DB connection (build on docker-compose.yml)
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/db_fileUp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC


# Private and public keys for JWT authentication
jwt.private-key=classpath:SecurityKeys/private.pem
jwt.public-key=classpath:SecurityKeys/public.pem
